(LOG-10499) - Criação do middleware para medir o tempo de retorno
comexio/php-utils pull request #33
Opened 2020-10-29 13:51 UTC by emanuelpoletto

## :package: Conteúdo
- Criação do middleware para medir o tempo de retorno

## :heavy_check_mark: Tarefa(s)
- [LOG-10499](https://logcomex.atlassian.net/browse/LOG-10499)

## :eyes: Tarefa de Code Review (CR)
- [LOG-10500](https://logcomex.atlassian.net/browse/LOG-10500)

2020-10-29 15:06 UTC, jeronimo-rocha reviewed
Só algumas observações

2020-10-29 15:06 UTC, jeronimo-rocha commented on bootstrap/start.php
> +            sleep(2);
esse sleep vai ficar fixo em 2 segundos mesmo?

2020-10-29 15:06 UTC, jeronimo-rocha commented on src/Dto/ResponseTimePayloadDto.php
> +    public $time_response = 0.0;
por favor, validar se o padrão não é camelCase, mesmo se baseando no banco

2020-10-29 15:06 UTC, jeronimo-rocha commented on tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php
> +    {
Este teste vai ficar vazio?

2020-10-29 17:17 UTC, emanuelpoletto commented on bootstrap/start.php
> +            sleep(2);
Sim. Supostamente, esse sleep só vai rodar nos testes do php-utils mesmo.

2020-10-29 17:19 UTC, emanuelpoletto commented on tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php
> +    {
Exato. É só uma classe fake usada nos testes acima e o método `save` não deve retornar nada mesmo ;)

2020-10-29 17:26 UTC, emanuelpoletto commented on src/Dto/ResponseTimePayloadDto.php
> +    public $time_response = 0.0;
Ótimo! Conferido... vamos de snake_case mesmo porque é o padrão que estamos seguindo lá no Elastic Search e essas variáveis correspondem diretamente ao atributo que será armazenado lá :+1:

2020-10-29 19:07 UTC, crysglodzienski requested changes

2020-10-29 19:07 UTC, crysglodzienski commented on README.md
> +    Logcomex\PhpUtils\Middleware\ResponseTimeLogMiddleware::class, // And after trace, you need the request log
acho que o importante é citar que esse middleware precisa vir antes de tudo

2020-10-29 19:07 UTC, crysglodzienski commented on src/Middlewares/ResponseTimeLogMiddleware.php
> +        $this->settings = config('responseTimeLog');
usar da config sugerida anteriormente, e importante validar se essa configuração não estiver feita, levantar exceção

2020-10-29 19:07 UTC, crysglodzienski commented on src/Middlewares/ResponseTimeLogMiddleware.php
> +    public function handle(Request $request, Closure $next)
tipar retorno, alterar doc da função para o retorno tipado

2020-10-29 19:07 UTC, crysglodzienski commented on src/Middlewares/ResponseTimeLogMiddleware.php
> +    public function getSetting(string $settingKey, $defaultValue = null)
tipar retorno e parametros

2020-10-29 19:07 UTC, crysglodzienski commented on tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php
> + * Class ResponseTimeLogUnitTest
```suggestion
 * Class ResponseTimeLogMiddlewareUnitTest
```

2020-10-29 19:07 UTC, crysglodzienski commented on README.md
> +    'api-name' => '',
já tem uma configuração de nome de api, usada nas outras apis.. acho válido usar ela arquivo app, variavel api-name

2020-10-29 19:07 UTC, crysglodzienski commented on README.md
> +$app->configure('responseTimeLog');
ai vc vai precisar aqui do `$app->configure('app');`

2020-11-03 21:58 UTC, crysglodzienski requested changes

2020-11-03 21:58 UTC, crysglodzienski commented on src/Middlewares/ResponseTimeLogMiddleware.php
> +    public function handle(Request $request, Closure $next): Response
Isso aqui vai dar erro.. o correto é ser JsonResponse. Que é quando vem do response()->json();

2020-11-03 21:58 UTC, crysglodzienski commented on src/Middlewares/ResponseTimeLogMiddleware.php
> +                    'PHU-007',
Creio que o projeto tenha uma enumerador de erro.. ErroreEnum se não to enganado, se não tiver criado criar por favor

2020-11-04 15:46 UTC, crysglodzienski approved these changes

2020-11-04 17:13 UTC, jorgelogcomex approved these changes

2020-11-04 17:58 UTC, merged